package com.staples.dashboard.app.constants;

public interface CTAConstants {

	
	String TASK_ID = "taskId";
	String LINK_TASK = "linkTask";
	String CUST_NUM = "custNum";
	String CTA_SEG = "ctaSeg";
	String CTA_SUB_SEG = "ctaSubSeg";
	String INSERT_DATE = "insertDate";
	String UPDATE_DATE = "updateDate";
	String SFDC_DATE = "sfdcDate";

	String GET_SEGMENT_LIST = "/segmentList";
	String GET_SEG_HDR_LABLES = "/segHdrLablesList";
	String GET_SEG_HDR_TEXT = "/segHdrText/{seg}/{segId}/{taskIdCombination}";
	String ADD_SEGMENT_DATA = "/addSegmentData";
	String SELECT_SEGMENT_LIST = "select * from HELIOS_OWN.sa_segment";
	String SELECT_SUBJECT_LABELS_LIST = "select SUBJECT_NAME from HELIOS_OWN.SA_SEG_SUBJECT_LABELS WHERE DISPLAY_FLAG='Y' ";
	String SELECT_SEG_HDR_LABLES_LIST = "select HDR_ID,HEADER_NAME from HELIOS_OWN.sa_seg_hdr_labels_1";
	String SELECT_SEG_HEADER_LABELS_IN_CLAUSE = "select * from HELIOS_OWN.SA_SEG_HDR_LABELS_1 where HDR_ID IN (:idsSet)";
	String SELECT_SEG_HEADER_TEXT = "select * from HELIOS_OWN.SA_SEG_HDR_TEXT_1 where seg = :seg and seg_id=:segId";
	String SELECT_SEG_HEADER_TEXT_SUB_DETAILS = "select SEG,SEG_ID,HEADER_IDS_SHOWN,TOTAL_HEADERS,HDR_1_STATIC_TEXT,HDR_1_PARAM_COUNT,HDR_2_STATIC_TEXT,"
			+ "HDR_2_PARAM_COUNT,HDR_3_STATIC_TEXT,HDR_3_PARAM_COUNT,HDR_4_STATIC_TEXT,HDR_4_PARAM_COUNT,HDR_5_STATIC_TEXT,HDR_5_PARAM_COUNT,HDR_6_STATIC_TEXT,"
			+ "HDR_6_PARAM_COUNT,HDR_7_STATIC_TEXT,HDR_7_PARAM_COUNT,HDR_8_STATIC_TEXT,HDR_8_PARAM_COUNT,HDR_9_STATIC_TEXT,HDR_9_PARAM_COUNT,HDR_10_STATIC_TEXT,"
			+ "HDR_10_PARAM_COUNT,HEADER_ID,PARAM_ID,PARAM_LABEL,PARAM_VALUE from HELIOS_OWN.sa_seg_hdr_text_1 sht LEFT JOIN HELIOS_OWN.sa_segment_sub_dtl_1 ssd ON sht.seg=ssd.CTA_SEGMENT "
			+ "AND sht.seg_id = ssd.CTA_SUB_SEGMENT where sht.seg=:seg AND sht.seg_id=:segId AND ssd.HEADER_ID in (select HEADER_ID from HELIOS_OWN.sa_seg_hdr_text_1 where seg = :seg and seg_id = :segId)";
	String SELECT_TASKIDCOMBINATION_SEGMENT_DETAIL = "SELECT TASK_ID_COMBINATION FROM HELIOS_OWN.SA_SEGMENT_DETAIL_1 WHERE TASK_ID_COMBINATION=:taskId";
	/*String INSERT_SEGMENT_DETAIL = "INSERT INTO SA_SEGMENT_DETAIL_1(TASK_ID_COMBINATION,LINK_TASKS,CUSTOMER_NUMBER,DIVISION,"
			+ "CTA_SEGMENT,CTA_SUB_SEGMENT,FYR_FPRD_FWK_FDY,SEG_DISP_STATUS,TASK_INSERT_DATE,TASK_UPDATE_DATE,"
			+ "SFDC_SENT_DATE,CREATED_BY,UPDATED_BY,REFRESHED_BY) VALUES(:taskId,:linkTask,:custNum,:division,"
			+ ":ctaSeg,:ctaSubSeg,:fyrFprdFwkFdy,:segDispStatus,:insertDate,:updateDate,:sfdcDate,:createdBy,"
			+ ":updatedBy,:refreshedBy)";*/
	/* old query commented*/
	/*String INSERT_SEGMENT_DETAIL = "INSERT INTO HELIOS_OWN.SA_SEGMENT_DETAIL(TASK_ID_COMBINATION,LINK_TASKS,CUSTOMER_NUMBER,DIVISION,"
			+ "CTA_SEGMENT,CTA_SUB_SEGMENT,FYR_FPRD_FWK_FDY,SEG_DISP_STATUS,TASK_INSERT_DATE,TASK_UPDATE_DATE,"
			+ "SFDC_SENT_DATE,CREATED_BY,UPDATED_BY,REFRESHED_BY,SFDC_TASK_ID , CONTACT_ID , SFDC_CONTACT_FULLNAME) VALUES(:taskId,:linkTask,:custNum,:division,"
			+ ":ctaSeg,:ctaSubSeg,:fyrFprdFwkFdy,:segDispStatus,:insertDate,SYSTIMESTAMP,:sfdcDate,:createdBy,"
			+ ":updatedBy,:refreshedBy,:sfdcTaskId,:contactId,:sfdcContactFullName)";*/
	/* new query start*/
	String INSERT_SEGMENT_DETAIL = "INSERT INTO HELIOS_OWN.SA_SEGMENT_DETAIL(TASK_ID_COMBINATION,LINK_TASKS,CUSTOMER_NUMBER,DIVISION,"
			+ "CTA_SEGMENT,CTA_SUB_SEGMENT,FYR_FPRD_FWK_FDY,SEG_DISP_STATUS,TASK_INSERT_DATE,TASK_UPDATE_DATE,"
			+ "SFDC_SENT_DATE,CREATED_BY,UPDATED_BY,REFRESHED_BY,SFDC_TASK_ID , CONTACT_ID , SFDC_CONTACT_FULLNAME, TASK_SUBJECT) VALUES(:taskId, (SELECT NVL(MAX(SEQ),0)+1 FROM(select ( ROW_NUMBER() OVER (PARTITION BY TASK_ID_COMBINATION ORDER BY TASK_ID_COMBINATION) * 1) AS SEQ from HELIOS_OWN.SA_SEGMENT_DETAIL WHERE TASK_ID_COMBINATION =:taskId)) ,:custNum,:division,"
			+ ":ctaSeg,:ctaSubSeg,:fyrFprdFwkFdy,:segDispStatus,:insertDate,SYSTIMESTAMP,:sfdcDate,:createdBy,"
			+ ":updatedBy,:refreshedBy,:sfdcTaskId,:contactId,:sfdcContactFullName,:subject)";
	
	/* old query commented*/
	//String INSERT_SEGMENT_DETAIL_WITHOUT_SFDC = "INSERT INTO HELIOS_OWN.SA_SEGMENT_DETAIL(TASK_ID_COMBINATION,LINK_TASKS,CUSTOMER_NUMBER,DIVISION,"
		//	+ "CTA_SEGMENT,CTA_SUB_SEGMENT,FYR_FPRD_FWK_FDY,SEG_DISP_STATUS,TASK_INSERT_DATE,TASK_UPDATE_DATE,"
			//+ "CREATED_BY,UPDATED_BY,REFRESHED_BY, CONTACT_ID , SFDC_CONTACT_FULLNAME) VALUES(:taskId,:linkTask,:custNum,:division,"
			//+ ":ctaSeg,:ctaSubSeg,:fyrFprdFwkFdy,:segDispStatus,:insertDate,SYSTIMESTAMP,:createdBy,"
			//+ ":updatedBy,:refreshedBy,:contactId,:sfdcContactFullName)";
	/* new query start*/
	String INSERT_SEGMENT_DETAIL_WITHOUT_SFDC = "INSERT INTO HELIOS_OWN.SA_SEGMENT_DETAIL(TASK_ID_COMBINATION,LINK_TASKS,CUSTOMER_NUMBER,DIVISION,"
		+ "CTA_SEGMENT,CTA_SUB_SEGMENT,FYR_FPRD_FWK_FDY,SEG_DISP_STATUS,TASK_INSERT_DATE,TASK_UPDATE_DATE,"
		+ "CREATED_BY,UPDATED_BY,REFRESHED_BY, CONTACT_ID , SFDC_CONTACT_FULLNAME, TASK_SUBJECT) VALUES(:taskId, (SELECT NVL(MAX(SEQ),0)+1 FROM(select ( ROW_NUMBER() OVER (PARTITION BY TASK_ID_COMBINATION ORDER BY TASK_ID_COMBINATION) * 1) AS SEQ from HELIOS_OWN.SA_SEGMENT_DETAIL WHERE TASK_ID_COMBINATION =:taskId)) ,:custNum,:division,"
		+ ":ctaSeg,:ctaSubSeg,:fyrFprdFwkFdy,:segDispStatus,:insertDate,SYSTIMESTAMP,:createdBy,"
		+ ":updatedBy,:refreshedBy,:contactId,:sfdcContactFullName,:subject)";
	
	String UPDATE_SEGMENT_DETAIL = "UPDATE HELIOS_OWN.SA_SEGMENT_DETAIL_1 SET LINK_TASKS=:linkTask, CUSTOMER_NUMBER=:custNum, DIVISION=:division, CTA_SEGMENT=:ctaSeg,"
			+ "CTA_SUB_SEGMENT=:ctaSubSeg, FYR_FPRD_FWK_FDY=:fyrFprdFwkFdy, SEG_DISP_STATUS=:segDispStatus, TASK_INSERT_DATE=:insertDate,"
			+ "TASK_UPDATE_DATE=:updateDate, SFDC_SENT_DATE=:sfdcDate, CREATED_BY=:createdBy, UPDATED_BY=:updatedBy, REFRESHED_BY=:refreshedBy WHERE "
			+ "TASK_ID_COMBINATION=:taskId";
	/*String INSERT_SEGMENT_COMMENT = "INSERT INTO SA_SEGMENT_COMMENTS_1(TASK_ID_COMBINATION,INSERT_DATE,COMMENT_TEXT,LOGGED_USER) "
			+ "VALUES(:taskId, :insertDate, :commentText, :loggedUser)";*/
	
	/* old query commented*/
	/*String INSERT_SEGMENT_COMMENT = "INSERT INTO HELIOS_OWN.SA_SEGMENT_COMMENTS(TASK_ID_COMBINATION,INSERT_DATE,COMMENT_TEXT,LOGGED_USER) "
			+ "VALUES(:taskId, :insertDate, :commentText, :loggedUser)";*/
	/* new query start*/
	String INSERT_SEGMENT_COMMENT = "INSERT INTO HELIOS_OWN.SA_SEGMENT_COMMENTS(TASK_ID_COMBINATION,INSERT_DATE,COMMENT_TEXT,LOGGED_USER,LINK_TASKS)"
			+ " VALUES(:taskId, :insertDate, :commentText, :loggedUser, (select max(LINK_TASKS) from HELIOS_OWN.SA_SEGMENT_DETAIL where TASK_ID_COMBINATION=:taskId))";
	
	String TASK_ID_PARAM = "taskId";
	String LINK_TASK_PARAM = "linkTask";
	String CUST_NUM_PARAM = "custNum";
	String DIVISION_PARAM = "division";
	String CTA_SEG_PARAM = "ctaSeg";
	String CTA_SUB_SEG_PARAM = "ctaSubSeg";
	String FYR_FPRD_FWK_FDY_PARAM = "fyrFprdFwkFdy";
	String SEG_DISP_STATUS_PARAM = "segDispStatus";
	String INSERT_DATE_PARAM = "insertDate";
	String UPDATE_DATE_PARAM = "updateDate";
	String SFDC_TASK_ID ="sfdcTaskId";
	String SFDC_DATE_PARAM = "sfdcDate";
	String CREATED_BY_PARAM = "createdBy";
	String UPDATED_BY_PARAM = "updatedBy";
	String REFRESHED_BY_PARAM = "refreshedBy";
	String COMMENT_TEXT_PARAM = "commentText";
	String LOGGED_USER_PARAM = "loggedUser";
	String SEG= "SEG";
	String SEG_ID="SEG_ID";
	String HEADER_IDS_SHOWN = "HEADER_IDS_SHOWN";
	String TOTAL_HEADERS="TOTAL_HEADERS";
	String HDR_1_STATIC_TEXT = "HDR_1_STATIC_TEXT";
	String HDR_1_PARAM_COUNT= "HDR_1_PARAM_COUNT";
	String HDR_2_STATIC_TEXT = "HDR_2_STATIC_TEXT";
	String HDR_2_PARAM_COUNT= "HDR_2_PARAM_COUNT";
	String HDR_3_STATIC_TEXT = "HDR_3_STATIC_TEXT";
	String HDR_3_PARAM_COUNT = "HDR_3_PARAM_COUNT";
	String HDR_4_STATIC_TEXT = "HDR_4_STATIC_TEXT";
	String HDR_4_PARAM_COUNT = "HDR_4_PARAM_COUNT";
	String HDR_5_STATIC_TEXT = "HDR_5_STATIC_TEXT";
	String HDR_5_PARAM_COUNT = "HDR_5_PARAM_COUNT";
	String HDR_6_STATIC_TEXT = "HDR_6_STATIC_TEXT";
	String HDR_6_PARAM_COUNT = "HDR_6_PARAM_COUNT";
	String HDR_7_STATIC_TEXT = "HDR_7_STATIC_TEXT";
	String HDR_7_PARAM_COUNT = "HDR_7_PARAM_COUNT";
	String HDR_8_STATIC_TEXT = "HDR_8_STATIC_TEXT";
	String HDR_8_PARAM_COUNT = "HDR_8_PARAM_COUNT";
	String HDR_9_STATIC_TEXT = "HDR_9_STATIC_TEXT";
	String HDR_9_PARAM_COUNT = "HDR_9_PARAM_COUNT";
	String HDR_10_STATIC_TEXT = "HDR_10_STATIC_TEXT";
	String HDR_10_PARAM_COUNT = "HDR_10_PARAM_COUNT";
	String NULL_SEG_AND_SEGID_ERROR_MSG = "Seg and Seg ID cannot be null";
	String NO_RECORD_FOUND_ERROR_MSG = "No Record found";
	String GET_SEG_DETAIL_INFO = "/getSegDetailInfo/{taskIdCombination}";
	String ADD_SEG_HDR_TEXT = "/addSegHdrText";
	String NULL_TASKIDCOMBINATION_ERROR_MSG = "TaskIdCombination cannot be null";
	String ADD_SEG_SUB_DETAIL = "/addSegSubDetail";
	String NULL_TASKIDCOMBINATION_HEADERID_PARAMID_ERROR_MSG = "TaskIdCombination,HeaderId,ParamId are mandatory";
	String GET_SEG_SUB_DETAIL = "/getSegSubDetail/{taskIdCombination}";
	String SELECT_TASKIDCOMBINATION_SEGMENT_SUB_DTL = "SELECT TASK_ID_COMBINATION FROM HELIOS_OWN.SA_SEGMENT_SUB_DTL_1 WHERE TASK_ID_COMBINATION=:taskIdCombination  AND HEADER_ID=:headerId AND PARAM_ID=:paramId";
	String INSERT_SEGMENT_SUB_DTL = "INSERT INTO HELIOS_OWN.SA_SEGMENT_SUB_DTL_1(TASK_ID_COMBINATION,CUSTOMER_NUMBER,DIVISION,CTA_SEGMENT,CTA_SUB_SEGMENT,FYR_FPRD_FWK_FDY,"
				+ "CTA_SEG_STATUS,TASK_INSERT_DATE,HEADER_ID,PARAM_ID,PARAM_LABEL,PARAM_VALUE,CREATED_BY,UPDATED_BY) "
				+ "VALUES (:taskIdCombination,:customerNumber,:divison,:ctaSegment,:ctaSubSegment,:fyrFprdFwkFdy,:ctaSegStatus,:taskInsertDate,:headerId,"
				+ ":paramId,:paramLabel,:paramValue,:createdBy,:updatedBy)";
	String INSERT_SEGMENT_SUB_DTL_PSMT = "INSERT INTO HELIOS_OWN.SA_SEGMENT_SUB_DTL_1(TASK_ID_COMBINATION,CUSTOMER_NUMBER,DIVISION,CTA_SEGMENT,CTA_SUB_SEGMENT,FYR_FPRD_FWK_FDY,"
			+ "CTA_SEG_STATUS,TASK_INSERT_DATE,HEADER_ID,PARAM_ID,PARAM_LABEL,PARAM_VALUE,CREATED_BY,UPDATED_BY) "
			+ "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	String UPDATE_SEGMENT_SUB_DTL = "UPDATE HELIOS_OWN.SA_SEGMENT_SUB_DTL_1 SET CUSTOMER_NUMBER=:customerNumber, DIVISION=:divison, CTA_SEGMENT=:ctaSegment, CTA_SUB_SEGMENT=:ctaSubSegment,"
				+ "FYR_FPRD_FWK_FDY=:fyrFprdFwkFdy, CTA_SEG_STATUS=:ctaSegStatus, TASK_INSERT_DATE=:taskInsertDate, PARAM_LABEL=:paramLabel, PARAM_VALUE=:paramValue, "
				+ "CREATED_BY=:createdBy, UPDATED_BY=:updatedBy WHERE TASK_ID_COMBINATION=:taskIdCombination  AND HEADER_ID=:headerId AND PARAM_ID=:paramId";
	String UPDATE_SEGMENT_SUB_DTL_PSMT = "UPDATE HELIOS_OWN.SA_SEGMENT_SUB_DTL_1 SET CUSTOMER_NUMBER=?, DIVISION=?, CTA_SEGMENT=?, CTA_SUB_SEGMENT=?,"
			+ "FYR_FPRD_FWK_FDY=?, CTA_SEG_STATUS=?, TASK_INSERT_DATE=?, PARAM_LABEL=?, PARAM_VALUE=?, "
			+ "CREATED_BY=?, UPDATED_BY=? WHERE TASK_ID_COMBINATION=?  AND HEADER_ID=? AND PARAM_ID=?";

	String SUCCESS = "SUCCESS";
	/*String SELECT_SEGMENT_SUB_DTL = "SELECT TASK_ID_COMBINATION,CUSTOMER_NUMBER,DIVISION,CTA_SEGMENT,CTA_SUB_SEGMENT,FYR_FPRD_FWK_FDY,CTA_SEG_STATUS,"
				+ "TO_CHAR(TASK_INSERT_DATE) TASK_INSERT_DATE,HEADER_ID,PARAM_ID,PARAM_LABEL,PARAM_VALUE,CREATED_BY,UPDATED_BY FROM HELIOS_OWN.SA_SEGMENT_SUB_DTL_1 WHERE TASK_ID_COMBINATION=:taskIdCombination";*/
	String INSERT_SEG_HDR_TEXT = "INSERT INTO  HELIOS_OWN.SA_SEG_HDR_TEXT_1(SEG, SEG_ID, HEADER_IDS_SHOWN, TOTAL_HEADERS, HDR_1_STATIC_TEXT, HDR_1_PARAM_COUNT, HDR_2_STATIC_TEXT, HDR_2_PARAM_COUNT, HDR_3_STATIC_TEXT, HDR_3_PARAM_COUNT, HDR_4_STATIC_TEXT, HDR_4_PARAM_COUNT, HDR_5_STATIC_TEXT, HDR_5_PARAM_COUNT, HDR_6_STATIC_TEXT, HDR_6_PARAM_COUNT, HDR_7_STATIC_TEXT, HDR_7_PARAM_COUNT, HDR_8_STATIC_TEXT, HDR_8_PARAM_COUNT, HDR_9_STATIC_TEXT, HDR_9_PARAM_COUNT, HDR_10_STATIC_TEXT, HDR_10_PARAM_COUNT) "
				+ "VALUES(:seg,:segId,:headerIds,:totalHdrs,:hdr1txt,:hdr1param,:hdr2txt,:hdr2param,:hdr3txt,:hdr3param,:hdr4txt,:hdr4param,:hdr5txt,:hdr5param,:hdr6txt,:hdr6param,:hdr7txt,:hdr7param,:hdr8txt,:hdr8param,:hdr9txt,:hdr9param,:hdr10txt,:hdr10param)";
	String UPDATE_SEG_HDR_TEXT = "UPDATE HELIOS_OWN.SA_SEG_HDR_TEXT_1 SET SEG=:seg, SEG_ID=:segId, HEADER_IDS_SHOWN=:headerIds, TOTAL_HEADERS=:totalHdrs, HDR_1_STATIC_TEXT=:hdr1txt, HDR_1_PARAM_COUNT=:hdr1param, HDR_2_STATIC_TEXT=:hdr2txt, HDR_2_PARAM_COUNT=:hdr2param, HDR_3_STATIC_TEXT=:hdr3txt, HDR_3_PARAM_COUNT=:hdr3param, HDR_4_STATIC_TEXT=:hdr4txt, HDR_4_PARAM_COUNT=:hdr4param, HDR_5_STATIC_TEXT=:hdr5txt, HDR_5_PARAM_COUNT=:hdr5param, HDR_6_STATIC_TEXT=:hdr6txt, HDR_6_PARAM_COUNT=:hdr6param, HDR_7_STATIC_TEXT=:hdr7txt, HDR_7_PARAM_COUNT=:hdr7param,"
				+ " HDR_8_STATIC_TEXT=:hdr8txt, HDR_8_PARAM_COUNT=:hdr8param, HDR_9_STATIC_TEXT=:hdr9txt, HDR_9_PARAM_COUNT=:hdr9param, HDR_10_STATIC_TEXT=:hdr10txt, HDR_10_PARAM_COUNT=:hdr10param WHERE SEG=:seg AND  SEG_ID=:segId";
	String SELECT_SEGMENT_DETAIL = "select SSD.TASK_ID_COMBINATION, SSD.SEG_DISP_STATUS, TO_CHAR(SSD.TASK_INSERT_DATE) TASK_INSERT_DATE, TO_CHAR(SSD.TASK_UPDATE_DATE) TASK_UPDATE_DATE, TO_CHAR(SSD.SFDC_SENT_DATE) SFDC_SENT_DATE, SSD.CREATED_BY, "
				+ "SSD.UPDATED_BY,SSD.REFRESHED_BY, SSC.COMMENT_TEXT, SSC.LOGGED_USER from HELIOS_OWN.SA_SEGMENT_DETAIL_1 SSD JOIN HELIOS_OWN.SA_SEGMENT_COMMENTS_1 SSC ON SSD.TASK_ID_COMBINATION = SSC.TASK_ID_COMBINATION where SSD.TASK_ID_COMBINATION = :taskIdCombination";
	String SEG_PARAM = "seg";
	String SEG_ID_PARAM = "segId";
	String IDS_SET_PARAM = "idsSet";	
	String TASK_ID_COMBINATION = "TASK_ID_COMBINATION";
	String TASK_ID_COMBINATION_PARAM = "taskIdCombination";
	String HEADER_ID_PARAM = "headerId";
	String PARAM_ID_PARAM = "paramId";
	String CUSTOMER_NUMBER = "CUSTOMER_NUMBER";
	String DIVISION = "DIVISION";
	String CTA_SEGMENT = "CTA_SEGMENT";
	String CTA_SUB_SEGMENT = "CTA_SUB_SEGMENT";
	String FYR_FPRD_FWK_FDY = "FYR_FPRD_FWK_FDY";
	String CTA_SEG_STATUS = "CTA_SEG_STATUS";
	String TASK_INSERT_DATE = "TASK_INSERT_DATE";
	String HEADER_ID = "HEADER_ID";
	String PARAM_ID = "PARAM_ID";
	String PARAM_LABEL = "PARAM_LABEL";
	String PARAM_VALUE = "PARAM_VALUE";
	String CONSTANT_PARAM_VALUE="CONSTANT_PARAM_VALUE";
	String DYNAMIC_PARAM_VALUE="DYNAMIC_PARAM_VALUE";
	String CREATED_BY = "CREATED_BY";
	String UPDATED_BY = "UPDATED_BY";
	String HEADER_IDS_PARAM = "headerIds";
	String TOTAL_HDRS_PARAM = "totalHdrs";
	String HDR_1_TXT_PARAM = "hdr1txt";
	String HDR_1_PARAM = "hdr1param";
	String HDR_2_TXT_PARAM = "hdr2txt";
	String HDR_2_PARAM = "hdr2param";
	String HDR_3_TXT_PARAM = "hdr3txt";
	String HDR_3_PARAM = "hdr3param";
	String HDR_4_TXT_PARAM = "hdr4txt";
	String HDR_4_PARAM = "hdr4param";
	String HDR_5_TXT_PARAM = "hdr5txt";
	String HDR_5_PARAM = "hdr5param";
	String HDR_6_TXT_PARAM = "hdr6txt";
	String HDR_6_PARAM = "hdr6param";
	String HDR_7_TXT_PARAM = "hdr7txt";
	String HRD_7_PARAM = "hdr7param";
	String HDR_8_TXT_PARAM = "hdr8txt";
	String HDR_8_PARAM = "hdr8param";
	String HDR_9_TXT_PARAM = "hdr9txt";
	String HDR_9_PARAM = "hdr9param";
	String HDR_10_TXT_PARAM = "hdr10txt";
	String HDR_10_PARAM = "hdr10param";
	String SEG_DISP_STATUS = "SEG_DISP_STATUS";
	String TASK_UPDATE_DATE = "TASK_UPDATE_DATE";
	String SFDC_SENT_DATE = "SFDC_SENT_DATE";
	String REFRESHED_BY = "REFRESHED_BY";
	String COMMENT_TEXT = "COMMENT_TEXT";
	String LOGGED_USER = "LOGGED_USER";
	String ONLY_NUMBER_VALUE_ALLOWED_ERROR_MSG = "Only numbers are allowed for header IDS";
	String REQUIRED_VAL_IS_NULL_ERROR_MSG = "Required values can-not be null";
	String SELECT_CUST_SFDC_INFO = "SELECT CONTACT_ID, CONTACT_FIRSTNAME, CONTACT_LASTNAME  FROM HELIOS_OWN.SA_CUSTOMER_SFDC_INFO WHERE MASTER_CUSTOMER_NUMBER=:custNum ORDER BY CONTACT_FIRSTNAME";
	String CONTACT_ID = "CONTACT_ID";
	String CONTACT_FIRSTNAME = "CONTACT_FIRSTNAME";
	String CONTACT_LASTNAME = "CONTACT_LASTNAME";
	String LABEL_PREFIX_TEXT = "LABEL_PREFIX_TEXT";
	String LABEL_NAME = "LABEL_NAME";
	String LABEL_SUFFIX_TEXT = "LABEL_SUFFIX_TEXT";
	String LABEL_HIDDEN_URL = "LABEL_HIDDEN_URL";

	
	
}